version: "3.1"
services:
  postgres:
    container_name: localPostgresSQLDB
    image: postgres
    environment:
      POSTGRES_DB: "hspt_db"
      POSTGRES_USER: "ado4ka"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5332:5432"